requires 'Moose';
requires 'Template';
requires 'Path::Class';
requires 'Data::GUID';
requires 'DateTime';
requires 'DateTime::Format::W3CDTF';
requires 'URI';
requires 'Text::MultiMarkdown';
requires 'YAML';
requires 'FindBin';
requires 'File::ChangeNotify';
requires 'File::HomeDir';
requires 'App::Daemon';
requires 'Try::Tiny';
requires 'HTML::Strip';
requires 'HTML::SocialMeta' => '0.72';
requires 'List::Util' => '1.45';
requires 'Readonly';
requires 'Web::Mention' => '0.6'; 
requires 'Mojolicious::Lite';
requires 'Capture::Tiny';
